### ISSUE TITLE
Voiced aspirates

### ISSUE THREAD

**Issue by cormacanderson** [cldf-clts/clts#119]
While true voiced aspirates /bʰ dʰ gʰ etc./ are, seemingly, possible https://en.wikipedia.org/wiki/Kelabit_language the vast majority of cases in our data are likely to be rather breathy voiced /bʱ dʱ gʱ etc./, as in languages of South Asia. I wonder if it would not be better to set up /bʰ dʰ gʰ etc./ as aliases of /bʱ dʱ gʱ etc./ and find another way to deal with the quite unusual Kelabit segments (note that on the wiki they arenʹt transcribed this way anyway) if they ever come up.
The status quo is yielding obvious errors in analysis. Check e.g. assa1263 here https://digling.org/phonobank/, where the same segments are represented in two different ways. We should be able to handle cases like this.

**Comment by LinguList** [comment]
Yes, these "true" voiced aspirates annoy me a lot. But whenever there are linguists in the room, also when we first presented CLTS, there is an uproar and a lot of arrogant discussion when I say that I don't believe they really exist. So the decision was driven by this very unpleasant experience: if phoneticians insist on this and know everything better, so be it.

**Comment by LinguList** [comment]
But the first version was exactly with those defined as alias. I am not against going back to this point.

**Comment by cormacanderson** [comment]
Yes, I would be in favour of this too. I don't remember when we changed this. We just have to be careful in case anyone has any Kelabit data...

Will I set up a pull-request then changing these to aliases?

**Comment by LinguList** [comment]
Yes, but since our tests rely on this distinction, it may involve quite some time to make sure the tests run again. You should also keep one thing in mind: you cannot simply define the superscript as an alias, but would have to define all possible consonants as aliases here. This is a hell of a work. You would have to add consonants that have so far not yet been encountered.

What is in fact easier is to leave the system as is and to add layers of normalization on top of our system from the code.

Such a layer, which would only apply to data ASSEMBLED, and not be generative (as the current system) would then allow us to break down from the voiced aspirated sounds to breathy-voiced sounds.

**Comment by LinguList** [comment]
We could define algebraic operations that would apply on a level of sounds to yield the corrected ones. For the phoneme inventory study, one would then apply these to break down the system to another level of comparability.

**Comment by LinguList** [comment]
Operations would be something like:
```python
if sound.voiced and sound.aspirated:
    sound.aspirated = None
    sound.breathiness = "breathy"
```

**Comment by LinguList** [comment]
The same operation could also be used to prevent breathiness to be applied for voiceless sounds:

```python
if sound.breathiness and sound.voicing == "voiceless":
    sound.voicing = "voiced"
```

**Comment by LinguList** [comment]
We could start defining this in a json format:

```json
{
  "voice-normalization": {
    "conditions": {"aspiration": "aspirated", "voicing": "voiced"},
    "modifications": {"aspiration": null, "breathiness": "breathy"}
  }
```

**Comment by LinguList** [comment]
The "voice-normalization" is the key for the operation. You could also just make a list:
```json
[
  {
    "conditions": {"aspiration": "aspirated", "voicing": "voiced"},
    "modifications": {"aspiration": null, "breathiness": "breathy"}
  },
  {
    "conditions": {"voicing": "voiceless", "breathiness": "breathy"},
    "modifications": {"voicing": "voiced"}
  }
]
```

**Comment by LinguList** [comment]
You can add a "note"  as a key for each operation to explain why it is applied.

**Comment by cormacanderson** [comment]
I was thinking here not of adding aliases for every possible breathy-voiced aspirate, but rather just redefining the current "voiced aspirates" as aliases of the existing breathy-voiced ones. There are ten relevant cases in consonants.tsv, 3 based on dʰ (dʰ, dʰː, dːʰ), 4 based on bʰ, 2 based on gʰ, and one on ɢʰ. My idea was to just respecify these (mostly fairly straightforward, if careful, copy-paste from existing aliases such as d̤). Would this work okay?

That way, voiced aspirates will still be possible, we just don't define any in consonants. tsv.

**Comment by LinguList** [comment]
If we define them or not won't make a difference: the system generates 
them anyway, but defining only 10 aliases is infelicitous: it will lead 
to other aspirated voiced stops being possible, but not the one we have. 
This is far worse than, as it is not consistent, so I still think my 
proposal to put this on top of the generative system is best for now, or 
something we could introduce as a new feature.

Define -> Generate -> Refine

**Comment by cormacanderson** [comment]
True about the inconsistency. It's also the fact that if true voiced aspirates actually do exist then it is better to not exclude them. The downside of what you suggest is that it seems to me like another layer of complexity, but you have a better handle on the overall code here than I do, so if you prefer this solution, then I'm happy enough to go along with it. Where would you like me to define these?

I think in principle I prefer the if statements, as they would give me the power to define illicit combinations, such as voiceless breathy voiced (as you have above). However, the morphological structure of something like `sound.voiced` or `sound.breathiness` is a bit unclear to me. Why not `sound.phonationːvoiced` and `sound.breathiness:breathy`. If you can explain this to me and tell me where to put these conditions, I would be happy to set them up.

**Comment by LinguList** [comment]
The more I think about the statements, the more I like them. CLTS has the task to reflect broadly what is out there, and to not do any decisions that would be too restrictive and then force us to be used only in a niche. As a result, we must be inclusive of these practices first, but we can add several layers of normalization and strictness. This can be done by:

1. proposing a "strictipa" (a sipa), where specific aliases are defined and the like, or by 
2. adding the possibility to reduce the sounds with the help of statements

We haven't explored the second possibility much, but we need this anyway at some point. So starting to set up the code for this is the best time now, and we can also use it when it comes to revising the phoneme inventory study.

**Comment by cormacanderson** [comment]
Okay, cool, we are in agreement then. I can start having a go at this if you can tell me where to do it and explain to me a little more (or tell me where to go to find out)  about the morphological structure of the sounds.

**Comment by LinguList** [comment]
I added a first file here: https://github.com/cldf-clts/clts/tree/master/pkg/normalizedtranscriptions/sipa.json

You can edit that file by expanding it (it is just json format).

**Comment by LinguList** [comment]
I do not fully understand what you mean by "morphological structure".

**Comment by cormacanderson** [comment]
Okay, cool, I'll add stuff there as it comes up. By morphological structure I mean in the if statements you had above, things like `sound.breathiness` and `sound.voiced`. 

In the json format that's not relevant though. Only one question: to add notes explaining what each does can I just put them outside the }s ?

**Comment by LinguList** [comment]
No, you'd have to add a new "key": "value" field there, key=note, value=your note.

**Comment by LinguList** [comment]
On the CLTS website, you now find all features described, if you click on teh sound.

**Comment by LinguList** [comment]
This also shows that I commited an error: Check here: https://clts.clld.org/parameters/voiced_retroflex_tap_consonant

we have "phonation: voiced" and phonation: unvoiced, etc.

**Comment by LinguList** [comment]
So for these features, I just use our feature system strictly. "none" (without `"` is the only additional value that we use, meaning: undefined, or `None` in Python = the feature is not assigned.

**Comment by LinguList** [comment]
If you have negative conditions, you can add a minus (`-`) in front of a feature value. So

```json
  "manner": "-tap"
```

**Comment by LinguList** [comment]
If you want to use many features at once, which can also happen, let us use this syntax for now:

```
  "manner": ["-tap", "-nasal"]
```

**Comment by LinguList** [comment]
But positive specification is always best.

**Comment by cormacanderson** [comment]
Okay, I modified that file. https://github.com/cldf-clts/clts/pull/124  Does that look right? All good with the syntax there, that is clear to me.
