### ISSUE TITLE
Repos content inconsistent

### ISSUE THREAD

**Issue by xrotwang** [cldf-clts/clts#126]
Trying to run through the release instructions, I hit the following problems:

1. `clts test` results in `ValueError: duplicate grapheme in markers.tsv:8: Ø`
   If I remove `Ø` from `pkg/transcriptionsystems/bipa/markers.tsv` the problem goes away.
2. Continuing with the fix for markers, I get:
   ```
   $ clts dist
   ...
   WARNING illegal feature value: consonant_articulation_with-friction
   ```

So currently, it seems a consistent release isn't possible - but we'd need one for a proper iecor lexibank dataset.

**Comment by cormacanderson** [comment]
@xrotwang I'm away at the minute with little internet but will have a chance to look into this and fix tomorrow evening.

**Comment by cormacanderson** [comment]
@xrotwang, these are separate issues. For 1) you can remove `Ø` from `pkg/transcriptionsystems/bipa/markers.tsv`, as you did before. For 2), it results from an invalid feature assignment which I have corrected [here](https://github.com/cldf-clts/clts/pull/127).
