### ISSUE TITLE
Syllabic modifier is empty in bipa/diacritics.tsv

### ISSUE THREAD

**Issue by LinguList** [cldf-clts/clts#129]
One of the syllabic modifier diacritics, the one above the sound, is not provided in the data, maybe also because it was not clear where it is actually used. This line should be deleted or updated. @xachab pointed to this in https://github.com/cldf-clts/pyclts/pull/46/

**Comment by XachaB** [comment]
Here is the faulty line:

https://github.com/cldf-clts/clts/blob/cccee296b1e54e653e1b4bea103bf0e870072765/pkg/transcriptionsystems/bipa/diacritics.tsv#L63

It should read:

```
◌̍	consonant	syllabicity	syllabic		up	
```

**Comment by XachaB** [comment]
I just submitted two PRs for the two possible fixes, you can pick the one you prefer :)

**Comment by XachaB** [comment]
wait, did you merge *both* ? This was an either/or situation

**Comment by LinguList** [comment]
Sorry, I did not understand this, but I corrected the cases, so the 
either or is an either now.

**Comment by XachaB** [comment]
Haha, sorry, I should have been clearer that I had prepared two merge requests, and the required action was picking only one and merging it ;). All good if it's fixed now

**Comment by LinguList** [comment]
The issue has been resolved now. The diacritics.tsv does no longer contain an empty element here.
