### ISSUE TITLE
Postvocalic aspiration in Urarina

### ISSUE THREAD

**Issue by CMUgarte** [cldf-clts/clts#141]
Converting the [northernperu dataset](https://github.com/lexibank/northernperu/tree/raw-data) into CLDF, I run into some CLTS sound class errors. Urarina faces processes of postvocalic aspiration in between syllables since the language does not accept consonants on coda position [(Olawsky 2006, pp. 40-1)](https://www.degruyter.com/document/doi/10.1515/9783110892932/html). The solution adopted so far is to transcribe it in the ortho-profile as:

| Grapheme | IPA |
| --- | --- |
| aʰ | !aʰ/a |
| iʰ | !iʰ/i |
| uʰ | !uʰ/u |

This strategy deletes the information. The grammar mentions that this phenomenon is optional (pp. 41). It appears, however, often throughout the dataset.

On the other hand, tanscribing it as `iʰtʃ    i ʰtʃ` does not quite reflect the insertion of /h/ after vowels. Below, I copy some of the CLTS errors I get:

| ID | LANGUAGE | CONCEPT | FORM | SEGMENTS |
|:----------------------------------------|:-----------|:------------------------------|:---------------------------|:-----------------------------------------------------------------------------------------|
| Urarina-102_near-1 | Urarina | 102_near | iʰtʃũṹ | i <s> <<ʰ>> </s> tʃ u ∼ !ṹ/u ∼ |
| Urarina-106_nose-1 | Urarina | 106_nose | aʰs̪í | a <s> <<ʰ>> </s> s !í/I |
| Urarina-112_toplay-1 | Urarina | 112_toplay | n̪ẽʰkuat̪ihján̪ãã | n e ∼ <s> <<ʰ>> </s> k u a t i h j !á/a n a ∼ a ∼ |

@LinguList or @xrotwang, how can we better represent this aspiration?

**Comment by LinguList** [comment]
Is there a problem in representing aspiration on vowels as "breathy"?

**Comment by LinguList** [comment]
Check [here](https://clts.clld.org/parameters/breathy_unrounded_open_front_vowel). This is allowed, just not the superscript h.

**Comment by FredericBlum** [comment]
@MuffinLinwist Have you adopted this solution for Urarina? Would be nice to have this solved for the NP-release. You can then just close this issue

**Comment by CMUgarte** [comment]
Yes, thanks @LinguList for the response. I'm closing the issue now.
