### ISSUE TITLE
Error with ASJP open back vowel?

### ISSUE THREAD

**Issue by seannyD** [cldf-clts/clts#147]
In the [asjpcode trascription system](https://clts.clld.org/contributions/asjpcode), the grapheme "u" is mapped to the BIPA "ɑ" (unrounded open back vowel). But according to the [ASJPcode Wikipedia entry](https://en.wikipedia.org/wiki/Automated_Similarity_Judgment_Program#ASJPcode), the grapheme "u" should be mapped to the BIPA "u" (unrounded close back vowel).

**Comment by LinguList** [comment]
True. Also in the Brown et al. paper:

```
u = high back vowel, rounded and unrounded [IPA: M, u]
```

I think this is an error I introduced as a doctoral student in LingPy.

**Comment by LinguList** [comment]
It should be mapped to `o` in ASJP code.

**Comment by LinguList** [comment]
@seannyD, if it is urgent for you to have a new release of the data, we can do it quickly, otherwise, we'd wait for more addons to accumulate now.
