### ISSUE TITLE
Dataset on Borrowed Sounds "segbo"

### ISSUE THREAD

**Issue by tresoldi** [cldf-clts/clts#21]
As hosted at https://github.com/segbo-db/segbo (Zenodo: https://zenodo.org/record/3633918).

**Comment by LinguList** [comment]
Eisen, Elad. 2019. The Typology of Phonological Segment Borrowing. MA thesis, the Hebrew University of Jerusalem. Online: https://www.researchgate.net/publication/341734023_The_Typology_of_Phonological_Segment_Borrowing.

Eisen, Elad, Eitan Grossman, Dmitry Nikolaev and Steven Moran. 2020. Defining and Operationalizing ‘Borrowability’ in Phonology. Societas Linguistica Europaea 53 (August 2020). Online: https://osf.io/gfqp9

Grossman, Eitan, Elad Eisen, Dmitry Nikolaev and Steven Moran. 2020a. SegBo: A Database of Borrowed Sounds in the World’s Languages. In Proceedings of the Twelfth International Conference on Language Resources and Evaluation (LREC 2020). Online: http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.654.pdf.

Grossman, Eitan, Elad Eisan, Dmitry Nikolaev and Steven Moran. 2020b. Revisiting the Uniformitarian Hypothesis: Can we detect recent changes in the typological frequencies of speech sounds? In Proceedings of the 13th International Conference on the Evolution of Language (EVOLANG 2020). Online: https://brussels.evolang.org/proceedings/papers/EvoLang13_paper_182.pdf.

**Comment by LinguList** [comment]
added the database to `sources/segbo`
