### ISSUE TITLE
Fix issues related to Phoible

### ISSUE THREAD

**Issue by tresoldi** [cldf-clts/clts#27]
After discussion with Cormac, these are the issues with Phoible graphemes that should be addressed:

- [ ] add `dlʷ` as an alias (voiced lateral affricate)
- [ ] add `d̠ʓ` as an alias ( ʒʲ )
- [ ] add `d̪l̪` as an alias (voiced lateral affricate)
- [ ] add `d̪ð̪` as an alias (voiced dental affricate)
- [ ] add `d͇z͇` (new sound, alveolar diacritic)
- [ ] add `i͓`, `u͓`, and `ɯ͓` as new sounds (frictionalised diacritic U+0353, might require new feature)
- [ ] decide on click notation/alias for `kǀ̪`, `kǀ͓x`, `kǀ͓ˀ`, `kǀ͓ˠʰ`, `kǁ͓xʰ`, `kǁ͓ˀ`, `kǂ͓ˡ`, `kǂ͓ˡx`, `kǂ͓ˡʰ`, `kǃ̪`, `kǃ͓`, `k‼`, `k‼x`, `k‼xʼ`, `k‼ʰ`, `k‼ʰʼ`, `k‼ʼ`, `qǀ`, `qǀʼ`, `qǁ`, `qǁʼ`, `qǂ`, `qǂʼ`, `qǃ`, `qǃʼ`, `qʘ`, `qʘʼ`, `ŋǂ͓ˡ`, `ŋ̤ǀ`, `ŋ̤ǀ͓`, `ŋ̤ǁ`, `ŋ̤ǂ`, `ŋ̤ǂ͓ˡ`, `ŋ̤ɡǃ`, `ŋ̥ǀ͓xˀ`, `ŋ̥ǁ͓ʰ`, `ŋ̥ǂxˀ`, `ŋ̥ǂʰ`, `ŋ̥ǂˀ`, `ŋ̥ǂ͓ˡxˀ`, `ŋ̥ǂ͓ˡʰ`, `ŋ̥ǂ͓ˡˀ`, `ŋ̥ǃˠˀ`, `ŋ̥ǃ̠ʰ`, `ŋ‼`, `ŋ‼ʱ`, `ɡǀ͓x`, `ɡǁ͓`, `ɡǂ͓ˡ`, `ɡǂ͓ˡx`, `ɡ̤ǀ`, `ɡ̤ǀ͓`, `ɡ̤ǁ`, `ɡ̤ǂ`, `ɡ̤ǂ͓ˡ`, `ɡ̰ǀ͓x`, `ɡ̰ǂx`, `ɡ̰ǂ͓ˡx`, `ɡ̰ǃx`, `ɡ‼`, `ɡ‼x`, `ɡ‼xʼ`, `ɡ‼ʱ`, `ɢǀ`, `ɢǀqʰ`, `ɢǁ`, `ɢǁqʰ`, `ɢǂ`, `ɢǃ`, `ɢǃqʰ`, `ɢʘ`, `ʔŋǀ`, `ʔŋǁ`, `ʔŋǂ`, `ʔŋǃ`, `ʔŋʘ`,
- [ ] correct entries for voiced alveolar lateral affricates `kʟ̥ʼ` and `kʟ͓̥ʼ` (we currently use pre-Unicode SIL extensions, `k` and `kʼ`, see [here](https://clts.clld.org/parameters/voiceless_velar_lateral_affricate_consonant) and [here](https://clts.clld.org/parameters/voiceless_velar_ejective_lateral_affricate_consonant))
- [ ] add `mw` as an alias (labialized bilabial)
- [ ] add `ndl` as an alias (voiced lateral affricate)
- [ ] add `aʲː` as an alias (long diphthong)
- [ ] add `ãʲ` as an alias (long diphthong)
- [ ] add `aʲ` as an alias (diphthong)
- [ ] add `eʲ` as an alias (diphthong)
- [ ] add `oʲ` as an alias (diphthong)
- [ ] add `õʲ` as an alias (diphthong)
- [ ] add `i̩ː` as an alias (even though arguably tautological)
- [ ] add `dl` as an alias (voiced lateral affricate)
- [ ] add `tl` as an alias (voiceless lateral affricate)
- [ ] decide on "less rounded" diacritic for consonants, particularly for `w̜` and `w̜ʲ`
- [ ] add co-articulated stops `ŋmʲ`, `ŋmʷ`, `ŋmˤ`, `ŋɡmb`, `ŋ̥m̥`
- [ ] decide what to do with missing tone that include other segmental or supra-segmental features: `˥˧̰`, `˥˩˩˥`, `˦ˀ`, `˦˥̰`, `˦̰`, `˧˨ˤ`, `˧˨̤`, `˧˩̤`, `˧˩̰`, `˨˩̤`, `↓˦˨`, `↓˦↓˦`
- [ ] add `ŋm` and `ŋmɡb` (co-articulated nasal stops)

In the same round, the following issues could be addressed as well:

- [ ] https://github.com/cldf-clts/clts/issues/25
- [ ] https://github.com/cldf-clts/clts/issues/13

**Comment by tresoldi** [comment]
Pinging @lingulist, @xrotwang ,@cormacanderson, @SimonGreenHill, @chrzyki

**Comment by LinguList** [comment]
> decide what to do with missing tone that include other segmental or supra-segmental features: ˥˧̰, ˥˩˩˥, ˦ˀ, ˦˥̰, ˦̰, ˧˨ˤ, ˧˨̤, ˧˩̤, ˧˩̰, ˨˩̤, ↓˦˨, ↓˦↓˦

Leave it: it is not serious to mark glottalization on the tone, if you can mark it on the vowel, etc., so it is an artifact of a rather problematic sampling.

**Comment by LinguList** [comment]
@tresoldi, not all the aliases need to be added, it is enough to contrast them with the CLTS counterpart, right?

**Comment by tresoldi** [comment]
@LinguList it is a matter of deciding whether to add them or not; in this list we have all graphemes used in Phoible (even if only once) that we though *might* be added. I agree with you on the tones, for example -- marking features such as nasalization or pharyngealization on the tone segment sound not only a bad practice, but wrong.

I would already add most of those listed, with the exception of clicks (I'd only add those which are transparent and easy) and the co-articulated ones. In particular, what is your take on the frictionalized vowels?

**Comment by LinguList** [comment]
Sorry, yes, frictionalized vowels would require a new feature. It is in fact not difficult to add the feature, so it could definitely be done. One could call it "frictionalization" and "with_fricture"?

**Comment by cormacanderson** [comment]
I don't know how many instances there were, but for the sake of completeness, I agree it's a good idea to add these. Probably better to call the new feature for the frictionalised vowels "with_friction".

**Comment by tresoldi** [comment]
When starting to prepare the PR, and also working on the inventories, I found more cases. They are co-articulated consonants that are either rejected or wrongly parsed as clusters.

I have quickly discussed them with @cormacanderson already. The changes would be:

- [ ] `kp` (IPA: k͡p), currently interpreted as "from voiceless velar stop to voiceless bilabial stop cluster"
- [ ] `gb` (IPA: ɡ͡b), currently interpreted as "from voiced velar stop to voiced bilabial stop cluster"
- [ ] `tp` (IPA: t͡p), currently interpreted as "from voiceless alveolar stop to voiceless bilabial stop cluster"
- [ ] `db` (IPA: d͡b), currently interpreted as "from voiced alveolar stop to voiced bilabial stop cluster"
- [ ] `qʡ` (IPA: q͡ʡ), currently interpreted as "from voiceless uvular stop to voiceless epiglottal stop cluster"
- [ ] `nm` (IPA: n͡m), currently giving an `UnknownSound`
- [ ] `ŋm` (IPA: ŋ͡m), currently giving an `UnknownSound`

Treatment would be in line with the one we currently have for /ɧ/. Note that the code already support these sounds, it is just parsing them in the wrong way and unable to render them as string:

```python
>>> str(c.bipa["voiceless labio-velar stop consonant"])
'<?><!>'
```

**Comment by cormacanderson** [comment]
- [ ] Also /lʒ/ should probably be listed as an alias for /ɮ/, cf. /tʃ/ etc. but in reverse

**Comment by LinguList** [comment]
I'd say, these phoible-related issues have now been decided to be handled by modifying **links** to clts, not CLTS itself.

**Comment by LinguList** [comment]
any remaining issues, e.g., that would require to modify CLTS (features, new sounds), should be added here.

**Comment by LinguList** [comment]
I close this as we have a new way to tackle problems now.
