### ISSUE TITLE
[New dataset] South American Phonological Inventory Database (SAPHON)

### ISSUE THREAD

**Issue by tresoldi** [cldf-clts/clts#30]
The well-known collection of the phonological inventories of South American indigenous languages, hosted as UC Berkeley. Data is in IPA.

https://linguistics.berkeley.edu/~saphon/en/phonemes.php

**Comment by LinguList** [comment]
So we start by making a list of the phonemes in `sources`. They are easy to parse, as they have an attribute `f`.

**Comment by LinguList** [comment]
`<span f="279" class="rare">ʏ</span>`

**Comment by LinguList** [comment]
Just added the code for parsing and the sound inventory.
