### ISSUE TITLE
[New dataset] Systèmes alphabétiques des langues africaines (AA)

### ISSUE THREAD

**Issue by tresoldi** [cldf-clts/clts#31]
Derived from the "Alphabets des langues africaines" (Unesco-SIL 1993), in IPA and with ISO language mapping: http://sumale.vjf.cnrs.fr/phono/PhonologieN.php

**Comment by LinguList** [comment]
addded code for parsing to sources with graphemes in `sala`.

**Comment by LinguList** [comment]
The URL of the sound inventories can be resolved as: 

```
http://sumale.vjf.cnrs.fr/phono/Reclangues1N.php?ChoixCellule={ID}
```

**Comment by tresoldi** [comment]
This was added by @LinguList as the `sala` source.
