### ISSUE TITLE
rhotic affricates

### ISSUE THREAD

**Issue by LinguList** [cldf-clts/clts#40]
@tresoldi, @cormacanderson, I need a list of these affricates, ideally exhaustive, with their name, their bipa character, and their features, Ideally in our standard form, so we can just add them. We also need a feature that we would add here. What would the feature be?

**Comment by cormacanderson** [comment]
The relevant cases are being dealt with under trilled release https://github.com/cldf-clts/clts/issues/45.

cf. also non-sibilant fricatives, which can form the second part of an affricate https://github.com/cldf-clts/clts/issues/51

Closing this for now
