### ISSUE TITLE
Dental diacritics

### ISSUE THREAD

**Issue by cormacanderson** [cldf-clts/clts#42]
The dental diacritic in segments such as the dental tap ɾ̪  is currently not being recognised. Examples:

- [ ] r̪ voiced dental trill consonant
- [ ] ɾ̪ voiced dental tap consonant
- [ ] ɾ̪̊ voiceless dental tap consonant
- [ ] ɾ̪ˠ velarized voiced dental tap consonant
- [ ] ɾ̪̊ʰ aspirated voiceless dental tap consonant
- [ ] ɾ̪ʲ palatalised voiced dental tap consonant
- [ ] ɹ̪̹̩ rounded voiced dental approximant consonant
- [ ] ɹ̪̰̩ creaky voiced dental approximant consonant
- [ ] ɹ̪ˠ velarized voiced dental approximant consonant
- [ ] ɫ̪ voiceless dental lateral fricative consonant
- [ ] ɮ̪ voiced dental lateral fricative consonant
- [ ] ɮ̪ʲ palatalized dental lateral fricative consonant
- [ ] t̪ɬ voiceless dental lateral affricate consonant

**Comment by cormacanderson** [comment]
@LinguList @tresoldi first issue. Do you need all of these names, or just a few examples here?

**Comment by LinguList** [comment]
All that are relevant, as I cannot GENERATE a dental, as its base, the manner, is "dental".

**Comment by cormacanderson** [comment]
Does that mean you need just the base though, or also secondary localisation etc.? For example, is  ɾ̪  enough, or do you need  ɾ̪ˠ and ɾ̪ʲ and  ɾ̪̊  as well?

**Comment by LinguList** [comment]
only the base, of course!
