### ISSUE TITLE
New feature: with-friction

### ISSUE THREAD

**Issue by cormacanderson** [cldf-clts/clts#47]
This is applicable to vowels, consonants, and clicks.
On vowels:
- [ ] i͓ with-friction unrounded close front vowel
- [ ] u͓ with-friction rounded close back vowel
- [ ] ɯ͓ with-friction unrounded close back vowel

On consonants:
- [ ] r͓ with-friction voiced alveolar trill consonant
- [ ] ɭ͓ with-friction voiced retroflex lateral approximant consonant
- [ ] ʟ͓ with-friction voiced velar lateral approximant consonant

On clicks:
- [ ] ǀ͓ with-friction voiceless dental click consonant
- [ ] ǁ͓ with-friction voiceless lateral click consonant
- [ ] ǂ͓ with-friction voiceless palatal click consonant
- [ ] ǃ͓ with-friction voiceless alveolar click consonant

cf. http://phoible.github.io/conventions/

**Comment by tresoldi** [comment]
It currently applies only to vowels, but I support extending it to consonants as well.

**Comment by LinguList** [comment]
Can we use this as an alternative feature for vowels? I don't want to include new features, but feature values are okay. Consider whistled sibilants: I added "sibilancy:whistled-sibilant".

**Comment by cormacanderson** [comment]
For vowels it's already in as a feature, frication: with-frication (simply friction would be better). For consonants it's a bit tricky to know where it would go. The articulation feature perhaps?

**Comment by LinguList** [comment]
I think, this could work, so we go for articulation = strong or none to articulation = strong or with-friction or none now.The order should also be okay for the grapheme then.
