### ISSUE TITLE
New feature: uvularized

### ISSUE THREAD

**Issue by cormacanderson** [cldf-clts/clts#48]
This is a new secondary localisation feature, relatively rare. I propose the modifier letter small capital inverted R, U+02B6 for this. The only data available has this on coronal stops and affricates.
- [ ] tx > tʶ uvularized voiceless alveolar stop consonant
- [ ] t̪x > t̪ʶ uvularized voiceless dental stop consonant
- [ ] dx > dʶ uvularized voiced alveolar stop consonant
- [ ] d̪x > d̪ʶ uvularized voiced dental stop consonant
- [ ] tʃx > tʃʶ uvularized voiceless post-alveolar affricate consonant
- [ ] dʒx > dʒʶ uvularized voiced post-alveolar affricate consonant

**Comment by tresoldi** [comment]
I think this should be allowed to vowels as well, it is not hard to find descriptions of uvularized vowels (besides the always-cited example of Northumbrian, that is even on Wikipedia).

**Comment by cormacanderson** [comment]
This is a good point @tresoldi. I haven't come across cases yet in our data, but they are out there.

**Comment by LinguList** [comment]
I'll map this to the release. "release:with-uvular-release". This is easier, as we use that already for some other parts, and I don't need to add a new feature, rather contrast one.
