### ISSUE TITLE
Implementation of with-nasal-release

### ISSUE THREAD

**Issue by cormacanderson** [cldf-clts/clts#49]
In parallel to the prenasalised feature, we can use a postposed nasal here.

From LAPSyD:
- [ ] kŋ > kⁿ with-nasal-release voiceless velar stop consonant
- [ ] kpŋm > kpⁿ with-nasal-release voiceless velar-and-labial stop consonant
- [ ] t̠n̠ > t̠ⁿ with-nasal-release retracted voiceless alveolar stop consonant
- [ ] t̠pn̠m > t̠pⁿ with-nasal-release retracted voiceless alveolar-and-bilabial stop consonant

From PHOIBLE:
- [ ] gm > gbⁿ with-nasal-release voiced velar-and-bilabial stop consonant
- [ ] km > kpⁿ with-nasal-release voiceless velar-and-bilabial stop consonant

I would propose to deal also with prestopped nasals here, (https://en.wikipedia.org/wiki/Pre-stopped_consonant).
From PHOIBLE:
- [ ] kŋ > kⁿ with-nasal-release voiceless velar stop consonant
- [ ] pm > pⁿ with-nasal-release voiceless bilabial stop consonant
- [ ] tn > tⁿ with-nasal-release voiceless alveolar stop consonant
- [ ] t̪n̪ > t̪ⁿ with-nasal-release voiceless dental stop consonant
- [ ] cn̠ > cⁿ with-nasal-release voiceless palatal stop consonant
- [ ] cɲ > cⁿ with-nasal-release voiceless palatal stop consonant
- [ ] dn > dⁿ with-nasal-release voiced alveolar stop consonant
- [ ] d̪n̪ > d̪ⁿ with-nasal-release voiced dental stop consonant
- [ ] ɖɳ > ɖⁿ with-nasal-release voiced retroflex stop consonant
- [ ] t̠n̠ > t̠ⁿ with-nasal-release retracted voiceless alveolar stop consonant
- [ ] ȶȵ > ȶⁿ with-nasal-release voiceless alveolo-palatal stop consonant

**Comment by cormacanderson** [comment]
I have since realised that we actually already have this feature. Amending the issue title.

**Comment by LinguList** [comment]
this is for those who do annotation then!
