### ISSUE TITLE
RTR on consonants

### ISSUE THREAD

**Issue by cormacanderson** [cldf-clts/clts#50]
We have retracted tongue root for vowels in https://github.com/cldf-clts/clts/blob/master/data/features.tsv, but not for consonants. There are some instances in our data:
- [ ] k̙ retracted-tongue root voiceless velar stop consonant
- [ ] ɡ̙ retracted-tongue root voiced velar stop consonant
- [ ] d̙ retracted-tongue root voiced alveolar stop consonant
- [ ] t̪̙ retracted-tongue root voiceless dental stop consonant
- [ ] ʕ̙ retracted-tongue root voiced pharyngeal fricative consonant

I have not come across any cases with ATR...

**Comment by cormacanderson** [comment]
Possibly as a feature value of relative articulation if you don't want to add new features?

**Comment by LinguList** [comment]
We don't have relative articulation for conosonants. I'd be inclined to ignore this now.

**Comment by LinguList** [comment]
sorry, we seem to have it.
