### ISSUE TITLE
Order of diacritics

### ISSUE THREAD

**Issue by cormacanderson** [cldf-clts/clts#54]
Assign write-order https://github.com/cldf-clts/pyclts/blob/dfddc2836bf66c83408e5c8a55b1f8f19d56551f/src/pyclts/models.py#L268-L276

Assign name-order https://github.com/cldf-clts/pyclts/blob/dfddc2836bf66c83408e5c8a55b1f8f19d56551f/src/pyclts/models.py#L277-L283

Cf. https://github.com/cldf-clts/pyclts/blob/dfddc2836bf66c83408e5c8a55b1f8f19d56551f/src/pyclts/models.py#L356-L371

**Comment by cormacanderson** [comment]
Assigning myself here and will update this after new features have been added. Once I update, I will assign also @tresoldi.

**Comment by tresoldi** [comment]
Phoible has its own order, correct? Maybe we should follow the same one?

**Comment by cormacanderson** [comment]
@LinguList I have changed both write order and name order accordingly and copy-paste below. Is this okay, or do you need more?
```
_write_order = dict(
        pre=['preceding'],
        post=[
            'raising', 'relative_articulation',
            'laminality', 'creakiness', 'phonation', 'ejection', 'syllabicity', 'voicing',
            'articulation',
            'nasalization', 'palatalization', 'labialization',
            'velarization',
            'pharyngealization', 'glottalization', 'breathiness', 'aspiration', 'release', 'duration'])
    _name_order = [
        'raising', 'relative_articulation',
        'articulation', 'preceding', 'syllabicity', 'nasalization', 'palatalization',
        'labialization', 'velarization',
        'pharyngealization', 'glottalization', 'aspiration', 'duration', 'release', 'voicing', 'creakiness',
        'breathiness', 'phonation', 'laminality', 'place', 'ejection', 'laterality',
        'sibilancy', 'manner']
```

**Comment by LinguList** [comment]
Yes, but please consider the new order:
```
    _write_order = dict(
        pre=['preceding'],
        post=[
            'raising', 'relative_articulation',
            'laminality', 'creakiness', 'phonation', 'ejection', 'syllabicity', 'voicing',
            'articulation',
            'nasalization', 'release', 'palatalization', 'labialization',
            'breathiness', 'aspiration', 'glottalization', 'velarization',
            'pharyngealization', 'friction', 'duration'
            ])


```

I adjusted this to have release (which is trilled release, etc.) before palatalization, or should it be the other way round?

**Comment by LinguList** [comment]
Please check this, as it reflects your order:

```
    _write_order = dict(
        pre=['preceding'],
        post=[
            'raising', 
            'relative_articulation',
            'laminality', 
            'creakiness', 
            'phonation', 
            'ejection', 
            'syllabicity', 
            'voicing',
            'articulation',
            'nasalization',
            'release',
            'palatalization',
            'labialization',
            'velarization',
            'pharyngealization',
            'glottalization',
            'breathiness',
            'aspiration',
            'friction',
            'duration'
            ])
```

**Comment by LinguList** [comment]
And this is the new name order:

```
    _name_order = [
        'raising', 
        'relative_articulation',
        'friction'
        'articulation', 
        'preceding', 
        'syllabicity', 
        'nasalization', 
        'palatalization',
        'labialization',
        'velarization',
        'pharyngealization', 
        'glottalization', 
        'aspiration', 
        'duration', 
        'release', 
        'voicing', 
        'creakiness',
        'breathiness', 
        'phonation', 
        'laminality', 
        'place', 
        'ejection', 
        'airstream',
        'manner', 
        ]
```

**Comment by cormacanderson** [comment]
Yes, that makes sense to have trilled release and nasalisation together. Well spotted. My main concern was to have first secondary articulation and then the aspiration.

**Comment by cormacanderson** [comment]
Seemingly not resolved yet, as replacements in https://github.com/cldf-clts/clts/pull/73 are not compatible with final order agreed above. Note velarisation after aspiration, while we agreed ...'palatalization', 'labialization', 'velarization', 'pharyngealization', 'glottalization', 'breathiness', 'aspiration'... Below the relevant cases:
Raw grapheme pʷˠʰ mapping was replaced from pʷˠʰ to pʷʰˠ. 
Raw grapheme pˠʰ mapping was replaced from pˠʰ to pʰˠ.
Raw grapheme pˤʰ mapping was replaced from pˤʰ to pʰˤ.
Raw grapheme qʷˤʰ mapping was replaced from qʷˤʰ to qʷʰˤ.
Raw grapheme qˤʰ mapping was replaced from qˤʰ to qʰˤ.
Raw grapheme tsˤʰ mapping was replaced from tsˤʰ to tsʰˤ.
Raw grapheme t̠ʃˤʰ mapping was replaced from tʃˤʰ to tʃʰˤ.
Raw grapheme t̪ˠʰ mapping was replaced from t̪ˠʰ to t̪ʰˠ.
Raw grapheme t̪ˠʰ|tˠʰ mapping was replaced from <NA> to tʰˠ.
Raw grapheme t̪ˤʰ mapping was replaced from t̪ˤʰ to t̪ʰˤ.
Raw grapheme ŋ̥ǃˠˀ mapping was replaced from ŋǃˠˀ to ŋǃˀˠ.

**Comment by LinguList** [comment]
I moved this issue to the pyclts repository issue [31](https://github.com/cldf-clts/pyclts/issues/31), where it makes more sense.
