### ISSUE TITLE
ȸ and ȹ ligatures

### ISSUE THREAD

**Issue by cormacanderson** [cldf-clts/clts#55]
I seem to remember us discussing the use of these before for the labiodental b̪ and p̪ respectively. Graphemically, they are preferable and Maddieson uses them, although they are not IPA. Minimally, they should be entered as aliases. I thought they were but cannot find them at https://clts.clld.org/values

**Comment by tresoldi** [comment]
It was discussed here: https://github.com/cldf-clts/clts-legacy/pull/123

**Comment by LinguList** [comment]
So you want the db as an alias for b̪ and the qp for p̪?

**Comment by cormacanderson** [comment]
Yes, lets do that

**Comment by tresoldi** [comment]
Agreed.
