### ISSUE TITLE
Source mapping for PHOIBLE, LAPSyD, JIPA

### ISSUE THREAD

**Issue by cormacanderson** [cldf-clts/clts#58]
This should happen after the code changes for the next update. Latest files are here https://github.com/cldf-clts/clts/pull/57.

**Comment by tresoldi** [comment]
I am uploading the mappings here, so they are easily accessible in the future.

[new.jipa.tsv.txt](https://github.com/cldf-clts/clts/files/5535486/new.jipa.tsv.txt)
[new.lapsyd.tsv.txt](https://github.com/cldf-clts/clts/files/5535487/new.lapsyd.tsv.txt)
[new.phoible.tsv.txt](https://github.com/cldf-clts/clts/files/5535488/new.phoible.tsv.txt)

**Comment by LinguList** [comment]
All fine, I have them locally as well.

**Comment by LinguList** [comment]
I included what could be included now. 

| id | valid | total | percent |
|:-------------|:--------|:--------|----------:|
| apics | 177 | 177 | 1.00 |
| bdpa | 1329 | 1466 | 0.91 |
| bdproto | 734 | 794 | 0.92 |
| beijingdaxue | 124 | 124 | 1.00 |
| chomsky | 45 | 45 | 1.00 |
| diachronica | 552 | 652 | 0.85 |
| eurasian | 1363 | 1562 | 0.87 |
| jipa | 933 | 959 | 0.97 |
| lapsyd | 767 | 795 | 0.96 |
| multimedia | 132 | 138 | 0.96 |
| nidaba | 1872 | 1936 | 0.97 |
| panphon | 6222 | 6334 | 0.98 |
| pbase | 811 | 1068 | 0.76 |
| phoible | 2921 | 3182 | 0.92 |
| powoco | 368 | 378 | 0.97 |
| ruhlen | 440 | 701 | 0.63 |
| saphon | 343 | 357 | 0.96 |
| segbo | 215 | 219 | 0.98 |
| wiki | 166 | 184 | 0.90 |
| 18 | | | 0.92 |

**Comment by LinguList** [comment]
This largely increases coverage. For datasets like saphon, segbo, and bdproto, we need to re-check the mapping with the new features I introduced. I close this for now.
