### ISSUE TITLE
phoible sounds that cannot be mapped (among others)

### ISSUE THREAD

**Issue by LinguList** [cldf-clts/clts#59]
ɾ̪ ɾ̪
ʐ͇ ʐ͇
ɫ̪ ɫ̪
ɾ̪ ᴅ
ð̪̺ ð̪̺
ɹ̪̩ ɹ̪̩
z͇ z͇
ʂ͇ ʂ͇
ts͇ ts͇
z͇ z̪͇|z͇
ɹ̪̹̩ ɹ̪̹̩
ɾ̪ˠ ɾ̪ˠ
ɯ͓ ɯ͓
k̙ k̙
ɗʒ ɗʒ
ɡǀ͓ ɡǀ͓
i̯au̯ i̯au̯
iou iou
ǁ͓ʰ kǁ͓ʰ
l̠˞ l̠˞
ʀʁ ʀʁ
s͇θ s̻θ
d̪ʒ d̪ʒ
ˀt̪ɬ ˀt̪ɬ
kɬ kɬ
ɖr̠ ɖr̠
ɖr̠͓ ɖr̠͓
ð͇ˠ ð͇ˠ
dz͇ d͇z͇
ⁿt͇s͇ʰ ⁿt͇s͇ʰ
s͇ s͇
ʃ͇ ʃ͇
t͇s͇ t͇s͇
ts͇ʰ ts͇ʰ
t͇s͇ʰ t͇s͇ʰ
ʈʂ͇ ʈʂ͇
ʒ͇ ʒ͇
t̪ʙ t̪ʙ
xʀ̥ xʀ̥
ŋ̥m̥ ŋ̥m̥
ð̙ˤ ð̪̙ˤ
ɹ̪̰̩ ɹ̪̰̩
ɹ̪ˠ ɹ̪̩ˠ
ɾ̪̊ ɾ̪̊
ɾ̪̊ʰ ɾ̪̊ʰ
ɾ̪ʲ ɾ̪ʲ
i͓ i͓
ʟ͓̥ ʟ͓̥
ɭ͓ ɭ͓
r͓ r̪͓|r͓
ɾ͓ ɾ͓
u͓ u͓
d̪l̪ d̪l̪
d̙ˤ d̙ˤ
t̪̙ˤ t̪̙ˤ
ʕ̙ ʕ̙
ɾ̪ ᴅ̪
ɾ̪̰ ᴅ̪̰
fʃ fʃ
ŋǂx ɡ̰ǂx
ŋǃx ɡ̰ǃx
ld ld
ʟ̝̊ɬ ɬʟ͓̥
ⁿbz mbz
ⁿd͇z͇ ⁿd͇z͇
r̠̙ r̠̙
st st
s̙ˤ s̙ˤ
ʃt ʃt
tθ̪ t̪θ̪
ˀy ˀy

**Comment by LinguList** [comment]
These sounds were wrongly specified, @cormacanderson, like, st is not possible as a cluster, as we do not allow these combinations, etc. If you want these to be included (I am against it, as I don't consider "st" as a valid sound), I'd need explicit feature values. The little "x", for example, is a feature that you did not introduce, and the like.

**Comment by cormacanderson** [comment]
In four places I would replace these as it's an error on my part:
ð̪̺ ð̪̺ mistake for ð̺ voiced apical dental fricative consonant
d̪ʒ d̪ʒ replace by dʒ
tθ̪ t̪θ̪ mistake for tθ voiceless dental affricate consonant
ˀy ˀy mistake for ˀj pre-glottalized voiced palatal approximant consonant

I suppose we leave blank the following:
ɗʒ ɗʒ
kɬ kɬ
ɖr̠ ɖr̠
i̯au̯ i̯au̯
iou iou
l̠˞ l̠˞
d̪l̪ d̪l̪
fʃ fʃ
ŋǂx ɡ̰ǂx
ŋǃx ɡ̰ǃx
ld ld
st st
ʃt ʃt

The rest should be dealt with by the outstanding issues:
ɾ̪ ɾ̪ see https://github.com/cldf-clts/clts/issues/42
ʐ͇ ʐ͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
ɫ̪ ɫ̪ see https://github.com/cldf-clts/clts/issues/42
ɾ̪ ᴅ see https://github.com/cldf-clts/clts/issues/42
ɹ̪̩ ɹ̪̩ see https://github.com/cldf-clts/clts/issues/42
z͇ z͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
ʂ͇ ʂ͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
ts͇ ts͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
z͇ z̪͇|z͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
ɹ̪̹̩ ɹ̪̹̩ see https://github.com/cldf-clts/clts/issues/42
ɾ̪ˠ ɾ̪ˠ see https://github.com/cldf-clts/clts/issues/42
ɯ͓ ɯ͓ see https://github.com/cldf-clts/clts/issues/47
k̙ k̙ see https://github.com/cldf-clts/clts/issues/50
ɡǀ͓ ɡǀ͓ see https://github.com/cldf-clts/clts/issues/47
ǁ͓ʰ kǁ͓ʰ see https://github.com/cldf-clts/clts/issues/47
ʀʁ ʀʁ see https://github.com/cldf-clts/clts/issues/44
s͇θ s̻θ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
ˀt̪ɬ ˀt̪ɬ we have the alveolar, added the dental to https://github.com/cldf-clts/clts/issues/42
ɖr̠͓ ɖr̠͓ see https://github.com/cldf-clts/clts/issues/47
ð͇ˠ ð͇ˠ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
dz͇ d͇z͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
ⁿt͇s͇ʰ ⁿt͇s͇ʰ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
s͇ s͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
ʃ͇ ʃ͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
t͇s͇ t͇s͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
ts͇ʰ ts͇ʰ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
t͇s͇ʰ t͇s͇ʰ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
ʈʂ͇ ʈʂ͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
ʒ͇ ʒ͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
t̪ʙ t̪ʙ see https://github.com/cldf-clts/clts/issues/44
xʀ̥ xʀ̥ see https://github.com/cldf-clts/clts/issues/44
ŋ̥m̥ ŋ̥m̥ see https://github.com/cldf-clts/clts/issues/44
ð̙ˤ ð̪̙ˤ see https://github.com/cldf-clts/clts/issues/50
ɹ̪̰̩ ɹ̪̰̩ see https://github.com/cldf-clts/clts/issues/42
ɹ̪ˠ ɹ̪̩ˠ see https://github.com/cldf-clts/clts/issues/42
ɾ̪̊ ɾ̪̊ see https://github.com/cldf-clts/clts/issues/42
ɾ̪̊ʰ ɾ̪̊ʰ see https://github.com/cldf-clts/clts/issues/42
ɾ̪ʲ ɾ̪ʲ see https://github.com/cldf-clts/clts/issues/42
i͓ i͓ see https://github.com/cldf-clts/clts/issues/47
ʟ͓̥ ʟ͓̥ see https://github.com/cldf-clts/clts/issues/47
ɭ͓ ɭ͓ see https://github.com/cldf-clts/clts/issues/47
r͓ r̪͓|r͓ see https://github.com/cldf-clts/clts/issues/47
ɾ͓ ɾ͓ see https://github.com/cldf-clts/clts/issues/47
u͓ u͓ see https://github.com/cldf-clts/clts/issues/47
d̙ˤ d̙ˤ see https://github.com/cldf-clts/clts/issues/50
t̪̙ˤ t̪̙ˤ see https://github.com/cldf-clts/clts/issues/50
ʕ̙ ʕ̙ see https://github.com/cldf-clts/clts/issues/50
ɾ̪ ᴅ̪ see https://github.com/cldf-clts/clts/issues/42
ɾ̪̰ ᴅ̪̰ see https://github.com/cldf-clts/clts/issues/42
ʟ̝̊ɬ ɬʟ͓̥ sir https://github.com/cldf-clts/clts/issues/47
ⁿbz mbz see https://github.com/cldf-clts/clts/issues/44
ⁿd͇z͇ ⁿd͇z͇ see https://github.com/cldf-clts/clts/issues/51 and https://github.com/cldf-clts/clts/issues/61
r̠̙ r̠̙ see https://github.com/cldf-clts/clts/issues/50
s̙ˤ s̙ˤ see https://github.com/cldf-clts/clts/issues/50

**Comment by cormacanderson** [comment]
The following should be resolved after implementation of https://github.com/cldf-clts/clts/issues/61:
s͇ > θ̠
z͇ > ð̠
ʃ͇ > ɹ̠̊˔
ʒ͇ > ɹ̠˔
ʂ͇ > ɻ̝̊
ʐ͇ > ɻ̝

t͇s͇ > tθ̠
d͇z͇ > dð̠
t̠ʃ͇ > tɹ̠̊˔
d̠ʒ͇ > dɹ̠˔
ʈʂ͇ > ʈɻ̝̊
ɖʐ͇ > ɖɻ̝

My understanding then is that we get these for free:
ⁿt͇s͇ʰ > ⁿtθ̠
ⁿd͇z͇ > ⁿdð̠

A PHOIBLE-specific mapping:
z̪͇|z͇ > ð̠

Implemented as aliases are
ð͇ > ð̠
θ͇ > θ̠ (not currently in PHOIBLE)

**Comment by LinguList** [comment]
so we add them as alias sounds?

**Comment by cormacanderson** [comment]
No, I think it better to do this as mapping from PHOIBLE, because this is a PHOIBLE-specific convention, not standard IPA usage. This is more of a reminder to myself. I can change the mappings in the .tsv file, but maybe best we resolve the issues first and then I can make the changes to the .tsv and then we run it again to see what still isn't accepted.

**Comment by LinguList** [comment]
But that means that you do not get anything "for free". That is
important! Anyway, there arent' more than the six sounds here.

**Comment by cormacanderson** [comment]
But surely if we have the base sound tθ̠, then the system will also parse ⁿtθ̠, right? Or should I specify that too?

**Comment by LinguList** [comment]
Sure, but if it is a correction for a transcription system the alias
form won't be detected.

**Comment by cormacanderson** [comment]
There's no alias here though: tθ̠ is a new base form that we defined in the discussion in https://github.com/cldf-clts/clts/issues/61 (the alias is rather tθ͇). ⁿtθ̠ is just that base form with prenasalisation, so it should be recognised, right? By "free" I mean that I don't specifically have to define ⁿtθ̠ as a new sound, because we have already defined its base.

**Comment by cormacanderson** [comment]
Or am I missing something? I realise I still have to map these to the sounds we have now defined, which is why I put up the reminder to myself...

**Comment by LinguList** [comment]
No, you are right, I thought you MEANT the aliases.
