### ISSUE TITLE
non-parsable sounds in lapsyd

### ISSUE THREAD

**Issue by LinguList** [cldf-clts/clts#60]
nm nm
n̠m n̠m
ɗ̪ʲ ɗ̪ʲ
ɽr ṛ
tx tx
βɾ βɾ
ŋ̊ǀh̃ ŋ̥ǀh̃
ŋ̊ǀx ŋ̥ǀx
ŋ̊ǀʔ ŋ̥ǀʔ
ŋ̊ǁh̃ ŋ̥ǁh̃
ŋ̊ǁx ŋ̥ǁx
ŋ̊ǁʔ ŋ̥ǁʔ
ŋ̊ǂh̃ ŋ̥ǂh̃
ŋ̊ǂx ŋ̥ǂx
ŋ̊ǂʔ ŋ̥ǂʔ
ŋ̊ǃh̃ ŋ̥ǃh̃
ŋ̊ǃx ŋ̥ǃx
ŋ̊ǃʔ ŋ̥ǃʔ
ɗ̪ ɗ̪
nmʲ nmʲ
n̠mʲ n̠mʲ
ɾ̪ ɾ̪
ᵗl̪ d̪l̪

see #59 for the same explanation.

**Comment by cormacanderson** [comment]
I suppose we leave the following blank, although I'd like to find a way to deal with those clicks @tresoldi you looked through:
ŋ̊ǀh̃ ŋ̥ǀh̃
ŋ̊ǀx ŋ̥ǀx
ŋ̊ǀʔ ŋ̥ǀʔ
ŋ̊ǁh̃ ŋ̥ǁh̃
ŋ̊ǁx ŋ̥ǁx
ŋ̊ǁʔ ŋ̥ǁʔ
ŋ̊ǂh̃ ŋ̥ǂh̃
ŋ̊ǂx ŋ̥ǂx
ŋ̊ǂʔ ŋ̥ǂʔ
ŋ̊ǃh̃ ŋ̥ǃh̃
ŋ̊ǃx ŋ̥ǃx
ŋ̊ǃʔ ŋ̥ǃʔ
ᵗl̪ d̪l̪

Dealt with by existing issues
nm nm see https://github.com/cldf-clts/clts/issues/44
n̠m n̠m see https://github.com/cldf-clts/clts/issues/44
ɗ̪ʲ ɗ̪ʲ see https://github.com/cldf-clts/clts/issues/42
βɾ βɾ see https://github.com/cldf-clts/clts/issues/44
ɗ̪ ɗ̪ see https://github.com/cldf-clts/clts/issues/42
nmʲ nmʲ see https://github.com/cldf-clts/clts/issues/44
n̠mʲ n̠mʲ see https://github.com/cldf-clts/clts/issues/44
ɾ̪ ɾ̪ see https://github.com/cldf-clts/clts/issues/42
ɽr ṛ see https://github.com/cldf-clts/clts/issues/53
tx tx see https://github.com/cldf-clts/clts/issues/48
