### ISSUE TITLE
Missing sounds in phoible now

### ISSUE THREAD

**Issue by LinguList** [cldf-clts/clts#63]
<NA>	aʊɪ	
<NA>	b˞	
<NA>	d̙ˤ	
<NA>	eəɪ	
<NA>	iau	
<NA>	iäu̽	
<NA>	iou	
<NA>	iɑu	
<NA>	iəɪ	
<NA>	iɛi̯	
<NA>	i̯ai	
<NA>	i̯ai̯	
<NA>	i̯au	
<NA>	i̯au̯	
<NA>	i̯ei̯	
<NA>	i̯eu̯	
<NA>	i̯oi	
<NA>	i̯uaː	
<NA>	i̯ui	
<NA>	i̯uo	
<NA>	i̯ũo	
<NA>	i̯æi	
<NA>	i̯ɛi	
<NA>	i̯ɛi̯	
<NA>	k˞	
<NA>	k˞ʰ	
<NA>	k̙	
<NA>	l̠˞	
<NA>	mbz	
<NA>	oəɪ	
<NA>	p˞	
<NA>	p˞ʰ	
<NA>	r̠̙	
<NA>	r̪͓|r͓	
<NA>	s̙ˤ	
<NA>	t̪̙ˤ	
<NA>	uai	
<NA>	uei	
<NA>	uei̯	
<NA>	uie	
<NA>	uiɛ	
<NA>	uɑi	
<NA>	uəi	
<NA>	u̯ai	
<NA>	u̯ai̯	
<NA>	u̯ei̯	
<NA>	u̯eu̯	
<NA>	u̯æi	
<NA>	u̯ɛi	
<NA>	u̯ɛi̯	
<NA>	w˞	
<NA>	w̜	
<NA>	w̜ʲ	
<NA>	yia	
<NA>	z̪͇|z͇	
<NA>	ð̪̙ˤ	
<NA>	ð̪̺	
<NA>	ŋ̥ǀ͓xˀ	
<NA>	ŋ̥ǂxˀ	
<NA>	ŋ̥ǂ͓ˡxˀ	
<NA>	əɪa	
<NA>	əʊɪ	
<NA>	ɡv	
<NA>	ɡ˞	
<NA>	ɡ̰ǀ͓x	
<NA>	ɡ̰ǂ͓ˡx	
<NA>	ɫ̪	
<NA>	ɹ̪̩	
<NA>	ɹ̪̩ˠ	
<NA>	ɹ̪̰̩	
<NA>	ɹ̪̹̩	
<NA>	ɻ̹̩	
<NA>	ʊ̯aɪ̯	
<NA>	ʕ̙	
<NA>	ˀy	
<NA>	˥˧̰	
<NA>	˥˩˩˥	
<NA>	˥̰	
<NA>	˦ˀ	
<NA>	˦˥̰	
<NA>	˦̰	
<NA>	˦↓˦	
<NA>	˧˨ˤ	
<NA>	˧˨̤	
<NA>	˧˩̤	
<NA>	˧˩̰	
<NA>	˨˩̤	
<NA>	˩̰	
<NA>	ᴅ	
<NA>	ᴅ̪	
<NA>	ᴅ̪̰	
<NA>	↓	
<NA>	↓˦˨	
<NA>	↓˦↓˦	
?	bz	
?	bzʷ	
?	b̤z̤	
?	dx	
?	d̠ʒx’	
?	d̪x	
?	d̪ʒ	
?	fʃ	
?	kf	
?	kl	
?	ld	
?	ps	
?	psʰ	
?	psʷ	
?	psʷʰ	
?	pʃʰ	
?	pʃ’	
?	qm	
?	qn	
?	st	
?	s̻θ	
?	tx	
?	t̠ʃx	
?	t̪x	
?	t̪ʙ	
?	xh	
?	xk	
?	xʀ̥	
?	ɖr̠͓	
?	ɗʒ	
?	ɡ̤ǀ͓	
?	ɡ̤ǂ͓ˡ	
?	ɣv	
?	ɬl	
?	ɬʟ͓̥	
?	ʀʁ	
?	ʃt	
?	ʍw	
?	ˀt̪ɬ

**Comment by LinguList** [comment]
We have 133 sounds unmapped, most of them, I think, we can just ignore them for now.

**Comment by cormacanderson** [comment]
There is a bare handful of these I think we should cover.

Under dental diacritics https://github.com/cldf-clts/clts/issues/42 are specified (let me know if you need the full .tsv notation):
- t̪ɬ, giving us ? ˀt̪ɬ
- ɫ̪
- ɹ̪, which should help with a few more

About five others can be sorted out through https://github.com/cldf-clts/clts/issues/50

These from UPSID, I can give specific mapping:
ᴅ, ᴅ̪, ᴅ̪̰, r̪͓|r͓, z̪͇|z͇, 

These should be mapped on a PHOIBLE-specific basis:
ð̪̺ > ð̺
ˀy > ˀj

Two more I specified here https://github.com/cldf-clts/clts/issues/44 and think we should add, as they are legit:
xʀ̥
t̪ʙ

The rest I think we should leave. Apart from the triphthongs, most of them are data problems.
