### ISSUE TITLE
Complete mapping of sources

### ISSUE THREAD

**Issue by tresoldi** [cldf-clts/clts#70]
With the improvements in `pyclts` and the extensions to the model/features here in clts-data, we need to review the mapping of the sources (also relying on `clts map`). I am listing them individually here, so they can be checked out:

  - [x] allenbai
  - [x] apics
  - [x] bdpa
  - [x] bdproto
  - [x] beijingdaxue
  - [x] chomsky
  - [x] diachronica
  - [x] eurasian
  - [x] jipa
  - [x] lapsyd
  - [ ] multimedia
  - [ ] nidaba
  - [ ] panphon
  - [ ] pbase
  - [x] phoible
  - [ ] powoco
  - [ ] ruhlen
  - [ ] sala
  - [ ] saphon
  - [ ] segbo
  - [ ] wiki

**Comment by tresoldi** [comment]
I am taking care of `phoible`, `lapsyd` and `jipa` first, as they are necessary for advancing the inventory study

**Comment by tresoldi** [comment]
`phoible` addressed with https://github.com/cldf-clts/clts/pull/71

**Comment by LinguList** [comment]
I'll occasionally cross things off here, so I'll just click them off.
